name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  video_trimmer:
    path: ../

  video_player: ^2.9.5
  file_picker: ^10.1.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
