name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 0.3.2
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^2.0.7
  video_player: ^0.11.0
  flutter_ffmpeg: ^0.3.0
  video_thumbnail: ^0.2.2
  path_provider: ^1.6.18
  intl: ^0.16.1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  pedantic: ^1.9.0

flutter:
