name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 0.3.5
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^3.0.0
  video_player: ^2.0.0
  flutter_ffmpeg: ^0.3.1
  video_thumbnail: ^0.2.5+1
  path_provider: ^2.0.1
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

flutter:
