name: flutter_video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 3.0.3
homepage: https://github.com/Kasun-thilina/video_trimmer

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.7.2
  ffmpeg_kit_flutter: ^6.0.3
  tmp_path: ^1.3.2
  get_video_thumbnail: ^0.7.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  path: ^1.9.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0

